nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ['^http://localhost:5173$', '^http://127\.0\.0\.1:5173$']
    allow_credentials: true
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept']
    expose_headers: ['Authorization', 'Link', 'Set-Cookie']
    max_age: 3600
  paths:
    '^/': ~
