nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['https://isl.yanasnytko.com']   # seul le front, pas le domaine API
    allow_methods: ['GET','POST','PUT','PATCH','DELETE','OPTIONS']
    allow_headers: ['Content-Type','Authorization','X-Requested-With','Accept']
    expose_headers: ['Authorization','Link','Set-Cookie']
    max_age: 3600
  paths:
    '^/api/': ~