# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\User: "auto"

    providers:
        app_user_provider:
            entity: { class: App\Entity\User, property: email }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: password
                success_handler: App\Security\JsonLoginSuccessHandler
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~

    access_control:
        - { path: ^/api, roles: PUBLIC_ACCESS, methods: [OPTIONS] } 
        - { path: ^/api/login$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/login_check$, roles: PUBLIC_ACCESS, methods: [POST] }
        - { path: ^/api/token/refresh$, roles: PUBLIC_ACCESS, methods: [POST] }
        - { path: ^/api/logout$, roles: PUBLIC_ACCESS, methods: [POST] }
        - { path: ^/api/events/\d+$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/events$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/organizers$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/organizers/\d+$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/api/organizers/\d+/events$, roles: PUBLIC_ACCESS, methods: [GET] }
        - {
              path: ^/api/upload$,
              roles: IS_AUTHENTICATED_FULLY,
              methods: [POST, OPTIONS],
          }
        - { path: ^/api/me$, roles: IS_AUTHENTICATED_FULLY, methods: [PUT] }
        - { path: ^/api/me/avatar$, roles: IS_AUTHENTICATED_FULLY, methods: [POST] }
        - { path: ^/api/my/events$, roles: IS_AUTHENTICATED_FULLY, methods: [GET] }
