controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login:
  path: /api/login

gesdinet_jwt_refresh_token:
  path: /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh

api_me:
  path: /api/me
  controller: App\Controller\Api\MeController
  methods: [GET]
